import { nanoid } from "nanoid"

// types
import type { MemoryCard, TableSize } from "@repo/db"
import type { CardCollectionWithCardsWithUser } from "@repo/db/types"
import type { ClientCardCollection } from "@repo/schema/collection"
import type {
  ClientSessionVariants,
  ClientSessionCard,
  SessionSettings
} from "@repo/schema/session"

// server
import { db } from "@repo/server/db"
import { ServerError } from "@repo/server/error"

// config
import { tableSizeMap } from "@repo/config/game"

/**
 * Generates a unique slug for a game session based on its type and mode.
 * 
 * - The slug starts with a prefix formed by taking the first two characters of the session's `type` 
 *   and the first three characters of the session's `mode`, both in lowercase.
 * - A unique 8-character identifier is appended to the prefix, generated by `nanoid` and replacing any 
 *   underscores (`_`) with hyphens (`-`).
 * 
 * This slug can be used as a unique identifier for the session.
 * 
 * @param {Object} session - The game session containing type and mode.
 * 
 * @returns {string} - The generated slug in the format `xx-yyy_xxxxxxxx`.
 */
export function generateSessionSlug(
  session: Pick<ClientSessionVariants, "mode" | "format">,
  isOffline: boolean = false
): string {
  const { mode, format } = session

  /*
   * Creates a prefix by slicing then merging the first
   * characters of session `mode` and `format`.
   */
  let prefix = `${mode.slice(0, 2).toLowerCase()}-${format.slice(0, 3).toLowerCase()}`

  if (isOffline) {
    prefix = 'off'
  }

  /* Prevents generating `_` symbol by nanoid. */
  const id = nanoid(8).replace(/_/g, '-')

  return `${prefix}_${id}`
}

/**
 * Generates an array of shuffled session cards from a given card collection for use in a game session.
 * 
 * - Selects a random subset of cards from the provided collection, based on half the collection's `tableSize` to ensure matched pairs.
 * - Duplicates each card, assigning unique keys to create pairs, and initializes `matchedBy` as `null`.
 * - Returns a shuffled array of session cards for randomized placement on the game board.
 * 
 * @param {ClientCardCollection} collection - The card collection used to generate session cards, containing a list of memory cards.
 * 
 * @returns {PrismaJson.SessionCard[]} - Array of session cards, each duplicated and shuffled for game use.
 */
export function generateSessionCards(
  collection: ClientCardCollection,
  tableSize: TableSize
): PrismaJson.SessionCard[] {
  const randomCards = collection.cards
    .sort(() => Math.random() - 0.5)
    .slice(0, tableSizeMap[tableSize] / 2)

  const sessionCards = randomCards.reduce((cards, card, index) => {
    const firstKey = index * 2
    const secondKey = index * 2 + 1

    return [
      ...cards,
      { key: firstKey, id: card.id, matchedBy: null },
      { key: secondKey, id: card.id, matchedBy: null }
    ] satisfies PrismaJson.SessionCard[]
  }, [] as PrismaJson.SessionCard[])

  return sessionCards.sort(() => Math.random() - 0.5)
}

/**
 * Pairs session cards with their corresponding image URLs from a card collection.
 * 
 * - Maps `collectionCards` to create a lookup object (`urlsMap`) where each card's ID corresponds to its image URL.
 * - Iterates over `sessionCards` and adds the matching `imageUrl` from `urlsMap` to each card object.
 * - Returns an array of `ClientSessionCard` objects, where each session card is enriched with the associated `imageUrl`.
 * 
 * @param {PrismaJson.SessionCard[]} sessionCards - The session cards that require image URLs.
 * @param {Pick<MemoryCard, 'id' | 'imageUrl'>[]} collectionCards - The collection of memory cards with image URLs to match with session cards.
 * 
 * @returns {ClientSessionCard[]} - A list of session cards with added `imageUrl` fields for client display.
 */
export function pairSessionCardsWithCollection(
  sessionCards: PrismaJson.SessionCard[],
  collectionCards: Pick<MemoryCard, 'id' | 'imageUrl'>[]
): ClientSessionCard[] {
  const urlsMap = collectionCards.reduce((urlsMap, card) => ({
    ...urlsMap,
    [card.id]: card.imageUrl
  }), {} as Record<string, string>)

  const cards = sessionCards.map((card) => ({
    ...card,
    imageUrl: urlsMap[card.id]
  }))

  return cards
}

/**
 * TODO: write doc
 * 
 * @param settings 
 * @returns 
 */
export async function verifyCollectionInAction(
  settings: Pick<SessionSettings, "collectionId" | "tableSize">
): Promise<CardCollectionWithCardsWithUser> {
  const { collectionId, tableSize } = settings

  /* Finding collection with the specified `collectionId` */
  const collection = await db.cardCollection.findUnique({
    where: { id: collectionId },
    include: { user: true, cards: true }
  })

  /**
   * Throws server error with `COLLECTION_NOT_FOUND` key if
   * collection not found with the specified `collectionId`.
   */
  if (!collection) {
    ServerError.throwInAction({
      key: "COLLECTION_NOT_FOUND",
      message: "Sorry, but we can't find the card collection you selected.",
      description: "Please, select another collection or try again later."
    })
  }

  /**
   * Throws server error with `TABLE_SIZE_CONFLICT` key if
   * collection and settings table sizes are incompatible.
   */
  if (tableSizeMap[tableSize] > tableSizeMap[collection.tableSize]) {
    ServerError.throwInAction({
      key: "TABLE_SIZE_CONFLICT",
      message: "Collection table size is too small.",
      description: "Table size of the selected collection is incompatible with your settings."
    })
  }

  return collection
}
